#!/usr/bin/env python3
"""P1-1 helper — generate `frontend/src/data.ts` from the SQLite DB.

Reads all tickers + their latest fundamentals + dividends and emits a typed
TypeScript snapshot. The Vite migration consumes this file as a static fallback
while still hydrating from `/api/tickers` for live updates.

Usage::

    python scripts/dump_tickers_to_data_ts.py
    python scripts/dump_tickers_to_data_ts.py --db ../mansa.db --out frontend/src/data.ts

The script is idempotent — running it twice produces the same file (modulo
the timestamp in the header).
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB = ROOT.parent / "mansa.db"
DEFAULT_OUT = ROOT / "frontend" / "src" / "data.ts"


HEADER = """/**
 * AUTO-GENERATED by scripts/dump_tickers_to_data_ts.py — DO NOT EDIT BY HAND.
 *
 * Source: SQLite tickers + fundamentals + latest dividends.
 * Regenerate with:  python scripts/dump_tickers_to_data_ts.py
 *
 * Generated: {ts}
 * Tickers:   {n}
 */

export interface TickerMeta {{
  t: string;
  full: string;
  n: string;
  s: string;
  c: number | null;
  v1: number | null;
  vol: number | null;
  per: number | null;
  pbr: number | null;
  roe: number | null;
  rdtDiv: number | null;
  div: number | null;
}}

export const S: TickerMeta[] = """


def fetch_rows(db_path: Path) -> list[dict]:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        """
        WITH ranked AS (
            SELECT symbol, date, close, volume,
                   ROW_NUMBER() OVER (PARTITION BY symbol ORDER BY date DESC) AS rn
            FROM prices
        ),
        latest_div AS (
            SELECT symbol, MAX(year) AS y FROM dividends GROUP BY symbol
        )
        SELECT t.symbol      AS full,
               t.name        AS n,
               t.sector      AS s,
               t.type        AS type,
               p1.close      AS c,
               p1.volume     AS vol,
               ROUND(
                 CASE WHEN p2.close > 0
                      THEN (p1.close - p2.close) / p2.close * 100.0
                      ELSE NULL END, 2)        AS v1,
               f.per, f.pbr, f.roe,
               d.amount      AS div_amount,
               d.yield_pct   AS rdt_div
        FROM tickers t
        LEFT JOIN ranked p1 ON p1.symbol = t.symbol AND p1.rn = 1
        LEFT JOIN ranked p2 ON p2.symbol = t.symbol AND p2.rn = 2
        LEFT JOIN fundamentals f ON f.symbol = t.symbol
            AND f.year = (SELECT MAX(year) FROM fundamentals WHERE symbol = t.symbol)
        LEFT JOIN latest_div ld ON ld.symbol = t.symbol
        LEFT JOIN dividends d ON d.symbol = t.symbol AND d.year = ld.y
        WHERE t.type = 'equity'
        ORDER BY t.symbol
        """
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def short_ticker(full: str) -> str:
    return full.split(".")[0]


def to_payload(rows: list[dict]) -> list[dict]:
    out = []
    for r in rows:
        out.append({
            "t": short_ticker(r["full"]),
            "full": r["full"],
            "n": r["n"],
            "s": r["s"] or "AUT",
            "c": r["c"],
            "v1": r["v1"],
            "vol": r["vol"],
            "per": r["per"],
            "pbr": r["pbr"],
            "roe": r["roe"],
            "rdtDiv": r["rdt_div"],
            "div": r["div_amount"],
        })
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--db", default=str(DEFAULT_DB))
    p.add_argument("--out", default=str(DEFAULT_OUT))
    args = p.parse_args()

    db_path = Path(args.db)
    out_path = Path(args.out)
    if not db_path.exists():
        print(f"[dump] DB not found: {db_path}", file=sys.stderr)
        return 1

    rows = fetch_rows(db_path)
    payload = to_payload(rows)

    text = HEADER.format(ts=datetime.utcnow().isoformat() + "Z", n=len(payload))
    text += json.dumps(payload, ensure_ascii=False, indent=2)
    text += ";\n"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"[dump] wrote {len(payload)} tickers → {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
